version: '3.8'

services:
  # 컨테이너 리소스 수집
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: hyuswim-cadvisor
    ports:
      - "127.0.0.1:8081:8080"  #내부 접근만 허용
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    networks:
      - hyuswim-monitor

  # Redis 메트릭 수집용 Exporter
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: hyuswim-redis-exporter
    environment:
      - REDIS_ADDR=redis://hyuswim-redis:6379
    ports:
      - "9121:9121"
    restart: always
    networks:
      - hyuswim-monitor

  # Prometheus (메트릭 수집기)
  prometheus:
    image: prom/prometheus:latest
    container_name: hyuswim-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: always
    networks:
      - hyuswim-monitor

  # Grafana (시각화)
  grafana:
    image: grafana/grafana:latest
    container_name: hyuswim-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - TZ=Asia/Seoul
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always
    networks:
      - hyuswim-monitor

volumes:
  prometheus_data:
  grafana_data:

networks:
  hyuswim-monitor:
    driver: bridge
